### ISSUE TITLE
Dangerous use of printf

### ISSUE THREAD

**Issue by heck-gd** [pathtofile/Sealighter#22]
https://github.com/pathtofile/Sealighter/blob/a21de27be9a3e0285a667b7f761b6bc5776fe955/sealighter/sealighter_util.cpp#L295

The util functions `log_messageA` and `log_messageW` pass an arbitrary message string to `printf`/`wprintf` as format template.

I noticed this while using the Microsoft-Windows-WinINet provider, which crashes Sealighter when encountering percent-encoded data in an URL.

**Comment by pathtofile** [comment]
Nice catch, I'm not sure how I missed it all this time. Thanks @heck-gd , code has been fixed and a new release made
